### ISSUE TITLE
Does it have any limitation with OData implementation?

### ISSUE THREAD

**Issue by chrisgate** [winstongubantes/matchasync#2]
I mean can i do everything OData implement with MatchaSync as long as i follow what is in MatchaSync documentation.

The reason of asking is that i went to re-watch full OData videos so i can take full advantage of this awesome SDK.

So i need to know.

Cheers and thank you for the SDK again.

Chris

**Comment by chrisgate** [comment]
@winstongubantes ??

**Comment by winstongubantes** [comment]
Hi @chrisgate, most of Odata queries are supported but not all like "expand". you can check the documentation of the supported queries [LINK](https://winstongubantes.github.io/MatchaSync/Query.html)

**Comment by chrisgate** [comment]
@winstongubantes Thanks for your reply.
I wish you can state it in the documentation which of Odata query is supported for now or not supported.

Using normal controller like the one in the CustomItemsController; do you think i can achieve having navigation properties (like what $expand does).

I am curious of what i can achieve with WebApi ,if there is any advantage of using it to Odata .

I am very keen on what i can achieve with this SDK.

Thanks @winstongubantes 

Cheers

**Comment by winstongubantes** [comment]
Hi @chrisgate , With Webapi you cannot achieve a query like the OData does, i will surely add the limitations in the documentation as soon as possible.
