### ISSUE TITLE
Any Update Or is okay to use in production

### ISSUE THREAD

**Issue by chrisgate** [winstongubantes/matchasync#5]
@winstongubantes Happy New Year !

Is any update coming and can you say this can be use in production today?

Thanks for this library and God bless you real good!.

Chris

**Comment by chrisgate** [comment]
@winstongubantes ?

**Comment by winstongubantes** [comment]
Hi @chrisgate ,

I apologize for the late response. Your question about when is it a production ready? The answer is yes, in fact i am using this on 2 of my clients project until this day. I only recommended this on a simple project that doesn't require per property history(i may implement this one day when needed) .
